# Generated by Django 5.0.4 on 2024-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_acceptance_service_abi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_weight_of_box',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Вес брутто короба, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight_of_box',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Вес нетто короба, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight_piece',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Вес нетто штуки, кг'),
        ),
    ]
