# Generated by Django 5.0.4 on 2024-04-20 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_acceptance_service_abi', '0003_alter_product_options_secondemailuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('SEND', 'ЗАКАЗ ОТПРАВЛЕН'), ('TAKE', 'ЗАКАЗ ПРИНЯТ В РАБОТУ'), ('CHAN', 'ЗАКАЗ ОТМЕНЕН'), ('COMP', 'ЗАКАЗ ВЫПОЛНЕН')], default='SEND', max_length=4, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_acceptance_service_abi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_acceptance_service_abi.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='order_acceptance_service_abi.OrderProduct', to='order_acceptance_service_abi.product'),
        ),
    ]
